
CREATE DATABASE crudnodejsmysql;

use crudnodejsmysql
CREATE TABLE CUSTOMER(
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15)
);


SHOW TABLES;

DESCRIBE CUSTOMER;